[project]
name = "comfyui_controlaltai_nodes"
description = "Quality fo Life Nodes from ControlAltAI. Flux Resolution Calculator, Flux Sampler, Flux Union ControlNet Apply, Noise Plus Blend, Boolean Logic Nodes."
version = "1.1.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/gseth/ControlAltAI-Nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "controlaltai"
DisplayName = "ControlAltAI_Nodes"
Icon = ""
